name: secure_notes
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  dynamic_color: ^1.6.9
  file_picker: ^6.1.1
  flutter:
    sdk: flutter
  flutter_locker: ^2.1.2
  flutter_secure_storage: ^9.0.0
  pointycastle: ^3.7.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
